get:
  tags:
    - Storage
  summary: Get storage data
  description: returns the storage data
  parameters:
    - name: path
      in: path
      description: path to storage
      required: true
      schema:
        type: string
  responses:
    "200":
      $ref: "#/components/responses/storage_successGetData"
    "400":
      $ref: "#/components/responses/badRequest"
    "401":
      $ref: "#/components/responses/unauthorized"
    "404":
      $ref: "#/components/responses/storage_notFound"
    default:
      $ref: "#/components/responses/default"
