get:
  tags:
    - Storage
  summary: Get storage data
  description: returns the storage data
  parameters:
    - name: path
      in: path
      description: path to storage
      required: true
      schema:
        type: string
  responses:
    "200":
      description: storage response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/defaultResponse"
    "400":
      $ref: "#/components/responses/badRequest"
    "401":
      $ref: "#/components/responses/unauthorized"
    "404":
      description: path Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    default:
      $ref: "#/components/responses/default"
