sudo: required
language: node_js
node_js:
- '8'
services:
- docker
- redis
branches:
  only:
  - master
before_install:
- docker run -d --name etcd -p 2380:2380 -p 4001:4001 quay.io/coreos/etcd:latest /usr/local/bin/etcd
  --data-dir=data.etcd --name "my-etcd" --cors='*' --initial-advertise-peer-urls http://0.0.0.0:2380
  --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://0.0.0.0:4001
  --listen-client-urls http://0.0.0.0:4001     --initial-cluster-state new
install:
- npm --registry http://npmhkube.ddns.net:4873 install
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
script:
- NODE_ENV=test npm test
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote set-url --push origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
- git remote -v
- git checkout -b version-branch
- npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
- git push origin version-branch:master --follow-tags
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
# - gcloud --quiet components update kubectl
deploy:
  skip_cleanup: true
  provider: script
  script: npm run build
  on:
    branch: master
env:
  global:
    secure: FwGku+HBx7IauPE0AffU/pRQOGJZM8TAhm0HEU23ersOnNuHpkGpX/ZoQD4mgEwCB6IsmyE97uzkecGQsyTIAZNFlM1EQlAVYdgkYJdhf5GYKytnPemC2vjS3GNW/dqeUPxZEOZTHIUjZVKQJizd1JVT4yVh7HFs8wdt0Ot6wGQVGmrbEesZ269WS7vCcNdximJOyb1hwx85ZDSRuxGbYr2vbnz2cO0iuS8z76z5lAiwCMZwLki98RfQMnCtQWugy0ISaimGoBaUjbx5Q/R5YkYVj0LvyJJPPjUUoJkDn0jdI+r44Qur12pCP+eI9s7IYHxc6gC1jvsG7/qm76D7z4gpaHKCVOCZYNdqP+PHwDvTZiz+2eI8EFxNYCShrXvt/lDODZjRcnmAMrsXKW4VQcahsT4K+9lPlGjup0AAEzQb2OOnsgCvVsxtSkhJNHU4G9x9LbubBwCGymI0eLsS2B1z22oph0fMhQwOzOgA/M8R/0Dax0PfDilhGmON0MTlRq6BwvFgT/EYEu7YHYkDCIe0zWBO91HyGHSRra4eUrBwWl7zm/ZTqtfxNBp+TzdwCQMaFRN9KVGp3vG5yhPNjFbUuJQg9ILStxTLVV+uSDRA75gql7DPryiTc3/Y9o6P/ADPDvxwhji5xf1CMqtai5TlnP5SDodyc0kJl/pMWBY=
